- DESIGN_DECISIONS.md
In order to improve the transparency as well as making the onboarding easier for contributors,
this PR creates a design decisions document. As several changes are coming in the following weeks, we
expect updates to this document very soon.
> Create design decisions document

- DESIGN_DECISIONS.md
Please find a proper description in the change itself.
> misc: Add design decision about bitnami-shell

- charts/_backup_restore.md.erb
- charts/backup_restore_pv_velero.md.erb
- charts/cassandra/_backup_restore.md.erb
- charts/mariadb-galera/_backup_restore.md.erb
- charts/mongodb/_backup_restore.md.erb
- charts/postgresql/_backup_restore.md.erb
- charts/redis-cluster/_backup_restore.md.erb
New section on Apache Cassandra documentation to explain how to backup and restore deployments on Kubernetes.
> Create backup restore section for Apache Cassandra

- charts/postgresql-ha/_enable_tls.md.erb
This PR is to document the new TLS parameters added in PR https://github.com/bitnami/charts/pull/6497
> Adds enable TLS to postgresql-ha documentation

- charts/cert-manager/_generate_acme_certificates.md.erb
- charts/cert-manager/_generate_self_signed_certificates.md.erb
- charts/cert-manager/_secure_ingress_resources.md.erb
Patch to fix the urls inside several cert manager contributions
> T34148 Fix urls for the Cert Manager contributions

- charts/redis/_deploy_custom_metrics_script.md.erb
Depends on: https://github.com/bitnami/charts/pull/6806
> redis: Add docs for setting up custom scripts in the metrics sidecar

- charts/sealed-secrets/install.md.erb
- common/_configure_ingress.md.erb
- common/_deploy_extra_resources.md.erb
- common/_enable_metrics.md.erb
- common/_enable_tls_ingress.md.erb
**Description of the change**
Add basic docs section for Sealed Secrets helm chart.
> [bitnami/sealed-secrets] Basic docs

- charts/geode/install.md.erb
- common/_configure_ingress.md.erb
- common/_deploy_extra_resources.md.erb
- common/_enable_diagnostic_mode.md.erb
- common/_enable_metrics_sidecar.md.erb
- common/_enable_tls_ingress.md.erb
- common/_scale_deployment.md.erb
Signed-off-by: juan131 <juanariza@vmware.com>
---
We're adding a new chart to the catalog: Apache Geode. See https://github.com/bitnami/charts/pull/7655
This PR adds the corresponding docs sections for this chart.
> [bitnami/geode] Basic docs

- charts/argo-cd/install.md.erb
- charts/argo-workflows/install.md.erb
- common/_configure_ingress.md.erb
- common/_deploy_extra_resources.md.erb
- common/_enable_metrics.md.erb
- common/_enable_tls_ingress.md.erb
Signed-off-by: Miguel A. Cabrera Minagorri <mcabrera@vmware.com>
> Add argo-workflows and argo-cd basic docs

- charts/contour-operator/install.md.erb
- common/_deploy_extra_resources.md.erb
- common/_enable_metrics.md.erb
Adding docs for Contour Operator, which is being added in https://github.com/bitnami/charts/pull/7675
> Add Contour Operator docs

- charts/redis/_backup_restore.md.erb
> [Redis][backup-restore] Improve docs about persistence

- charts/kafka/_external_access.md.erb
The latest charts have some differences with the doc for NodePort access.
> Correct NodePort access doc

- charts/discourse/_upgrade.md.erb
Signed-off-by: Marcos Bjoerkelund <marcos@bitnami.com>
> Add new Discourse 7.0.0 chart major update notes

- _open_cve_policy.md.erb
- publish-docker-image.md.erb
Signed-off-by: Carlos Rodriguez Hernandez <carlosrh@vmware.com>
> Change method to obtain CVE scan results

- charts/redmine/_upgrade.md.erb
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>
> docs(redmine): :memo: Update upgrades notes

- charts/harbor/_upgrade.md.erb
Found a typo in the upgrading notes...
Signed-off-by: Andreas Lindhé <andreas@lindhe.io>
> [bitnami/harbor] Use --namespace for POSTGRESQL_PVC

- charts/argo-workflows/_upgrade.md.erb
This PR is complementary to https://github.com/bitnami/charts/pull/10178
> [bitnami/argo-workflows] Update upgrade notes 'To 2.0.0'

- charts/postgresql-ha/_enable_tls.md.erb
Add a new section for client certificate authentication and improve the introduction.
Signed-off-by: Jose Antonio Carmona <jcarmona@vmware.com>
> [bitnami/postgresql-ha] Document client certificate authentication

- charts/geode/install.md.erb
- common/_configure_ingress.md.erb
- common/_deploy_extra_resources.md.erb
- common/_enable_diagnostic_mode.md.erb
- common/_enable_metrics_sidecar.md.erb
- common/_enable_tls_ingress.md.erb
- common/_expose_deployment.md.erb
- common/_scale_deployment.md.erb
Signed-off-by: Miguel Ruiz <miruiz@vmware.com>
The bitnami/geode chart has been deprecated. This PR removes its page from the docs.
> [bitnami/geode] Remove docs

- charts/contour-operator/install.md.erb
- common/_deploy_extra_resources.md.erb
- common/_enable_metrics.md.erb
> [bitnami/contour-operator] Deprecate contour operator

- charts/harbor/_expose_service.md.erb
- charts/harbor/_upgrade.md.erb
> [bitnami/harbor-notary-*] Deprecate harbor notary

- _get_started_kubernetes.md.erb
- _scale_deployment.md.erb
- common/_install_kubernetes.md.erb
- common/_install_tac.md.erb
- common/troubleshoot_helm_chart_issues.md.erb
- deploy_chart_tmc_tkg.md.erb
This PR adapts the "get started" & common guides to use the OCI format for Helm.
> docs: Adapt get-started & common guides to use OCI format for Helm

- charts/redis-cluster/_compare_solutions.md.erb
I found the comparison doc very confusing. I believe this was a typo, right?
> Fix redis comparison doc
